# Generated by Django 2.2.5 on 2019-10-12 14:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polygon', '0013_auto_20191012_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='generator',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generator',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='test',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', models.TextField(blank=True)),
                ('tested', models.BooleanField(default=False)),
                ('message', models.CharField(blank=True, max_length=128)),
                ('verdict', models.CharField(blank=True, choices=[('0', 'OK'), ('1', 'WA'), ('2', 'PE'), ('8', 'UNEXPECTED_EOF')], max_length=64)),
                ('submission_type', models.CharField(choices=[('CPP17', 'gcc C++ 17'), ('PYTHON3', 'python 3.7')], max_length=64)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polygon.Problem')),
            ],
        ),
    ]
